project_name: 'msics-toolseg'

# dataset details
dataset:
  data_csv_path: 'SankaraMSICS/cataract-msics-data.csv'
  image_dir: 'SankaraMSICS/images'
  mask_dir: 'SankaraMSICS/masks'
  phase_one_hot: TRUE
  instrument_labels: ["blade","cautery","conjunctivital_scissors","crescent_blade","dialer","hoskins_forceps","hydrodisection_cannula","keratome","rhexis_needle","sideport","simcoe_cannula","vectis","visco_cannula"]

seed: 42

# training details
init_lr: 1e-4
n_epochs: 2
batch_size: 1
num_workers: 14
fold: 0
patience: 10

data_aug: 0

pretrained: False

# saving checkpoints
save_dir: 'weights/'
save_freq: 1

#inference
weights: 'weights/experiment_folder'
output_dir: 'output/'

condition:
  phase: 'none'  # 'none', 'pcd', 'pcd-gated'
is_debug: False

# model details
model:
  name: 'unet' # 'unet', 'panet', 'ternausnet'
  n_channels: 3
  n_classes: 14
  n_phases: 19